spring:
  application:
    name: api-eureka
    cloud:
  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/