server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscustomer
          uri: lb://api-customer
          predicates:
            - Path=/api/v1/customers/**
        - id: mswallet
          uri: lb://api-wallet
          predicates:
            - Path=/api/v1/wallets/**
        - id: msmargins
          uri: lb://api-margins
          predicates:
            - Path=/api/v1/margins/**
        - id: mscaard
          uri: lb://api-card
          predicates:
            - Path=/api/v1/apiCard/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway